Summary: Radius Rapid Rotate (R3) Log Rotater
Name: radius-rapid-rotate
Version: 1.1.0
Release: 1%{?dist}
License: MIT
URL: http://www.prophecy.net.nz
Group: Applications/Internet
Source0: radius-rapid-rotate-%{version}.tar.bz2
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch: noarch

Requires: perl

%description
Provides a regularly executed script to rotate logfiles generated by FreeRadius, with
the rotation period controlled by cron.


%prep
%setup -q -n radius-rapid-rotate-%{version}

%build


%install
rm -rf $RPM_BUILD_ROOT

# install application files and resources
mkdir -p $RPM_BUILD_ROOT%{_bindir}
cp bin/radius-rapid-rotate.pl $RPM_BUILD_ROOT%{_bindir}/radius-rapid-rotate

# install cron configuration
mkdir -p $RPM_BUILD_ROOT%{_sysconfdir}/cron.d/
install -m 644 resources/radius-rapid-rotate.cron $RPM_BUILD_ROOT%{_sysconfdir}/cron.d/radius-rapid-rotate

# make default directories
mkdir -p $RPM_BUILD_ROOT%{_localstatedir}/log/radius/archive
mkdir -p $RPM_BUILD_ROOT%{_localstatedir}/log/radius/R3tmp

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root)
%doc docs/COPYING docs/README
%attr(644,root,root) %config(noreplace) %{_sysconfdir}/cron.d/radius-rapid-rotate
%{_bindir}/radius-rapid-rotate
%{_localstatedir}/log/radius/archive
%{_localstatedir}/log/radius/R3tmp

%changelog
* Mon Jun 11 2012 Jethro Carr <jethro.carr@prophecy.net.nz> 1.1.0
- Support for archiveal directory on mounted shares.
* Tue Jun 05 2012 Jethro Carr <jethro.carr@prophecy.net.nz> 1.0.1
- Adjustment to archived file naming scheme.
* Fri Jun 01 2012 Jethro Carr <jethro.carr@prophecy.net.nz> 1.0.0
- Built new RPM package.

